name: Petclinic CICD 

on:
  push:
    branches: [ "main" ]
    
jobs:
  # build the application
  build:

    runs-on: self-hosted

    steps:
    - name: Code checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Set up Maven
      run: sudo apt install maven -y
        
    - name: Build with Maven
      run: mvn clean install

  # deployment of application
  deploy:
      runs-on: self-hosted
      needs: build

      steps:
      - name: Deploy to Tomcat
        run: cp /home/ubuntu/actions-runner/_work/Petclinic/Petclinic/target/petclinic.war /var/lib/tomcat9/webapps/
        
